CREATE TABLE ECF_TURNO (
  ID SERIAL  NOT NULL ,
  DESCRICAO VARCHAR(10)    ,
  HORA_INICIO VARCHAR(8)    ,
  HORA_FIM VARCHAR(8)      ,
PRIMARY KEY(ID));



CREATE TABLE IBPT (
  ID SERIAL  NOT NULL ,
  NCM VARCHAR(8)    ,
  EX CHAR(2)    ,
  TIPO CHAR(1)    ,
  DESCRICAO TEXT    ,
  NACIONAL_FEDERAL DECIMAL(18,6)    ,
  IMPORTADOS_FEDERAL DECIMAL(18,6)    ,
  ESTADUAL DECIMAL(18,6)    ,
  MUNICIPAL DECIMAL(18,6)    ,
  VIGENCIA_INICIO DATE    ,
  VIGENCIA_FIM DATE    ,
  CHAVE VARCHAR(6)    ,
  VERSAO VARCHAR(6)    ,
  FONTE VARCHAR(34)      ,
PRIMARY KEY(ID));



CREATE TABLE LOGSS (
  ID SERIAL  NOT NULL ,
  TTP INTEGER    ,
  PRODUTO INTEGER    ,
  R01 INTEGER    ,
  R02 INTEGER    ,
  R03 INTEGER    ,
  R04 INTEGER    ,
  R05 INTEGER    ,
  R06 INTEGER    ,
  R07 INTEGER      ,
PRIMARY KEY(ID));



CREATE TABLE ECF_TIPO_PAGAMENTO (
  ID SERIAL  NOT NULL ,
  CODIGO CHAR(3)    ,
  DESCRICAO VARCHAR(20)    ,
  TEF CHAR(1)    ,
  IMPRIME_VINCULADO CHAR(1)    ,
  PERMITE_TROCO CHAR(1)    ,
  TEF_TIPO_GP CHAR(1)    ,
  GERA_PARCELAS CHAR(1)      ,
PRIMARY KEY(ID));



CREATE TABLE ECF_FUNCIONARIO (
  ID SERIAL  NOT NULL ,
  NOME VARCHAR(100)    ,
  TELEFONE VARCHAR(10)    ,
  CELULAR VARCHAR(10)    ,
  EMAIL VARCHAR(250)    ,
  COMISSAO_VISTA DECIMAL(18,6)    ,
  COMISSAO_PRAZO DECIMAL(18,6)    ,
  NIVEL_AUTORIZACAO CHAR(1)      ,
PRIMARY KEY(ID));



CREATE TABLE ECF_IMPRESSORA (
  ID SERIAL  NOT NULL ,
  NUMERO INTEGER    ,
  CODIGO VARCHAR(10)    ,
  SERIE VARCHAR(30)    ,
  IDENTIFICACAO VARCHAR(250)    ,
  MC CHAR(2)    ,
  MD CHAR(2)    ,
  VR CHAR(2)    ,
  TIPO VARCHAR(7)    ,
  MARCA VARCHAR(30)    ,
  MODELO VARCHAR(30)    ,
  MODELO_ACBR VARCHAR(30)    ,
  MODELO_DOCUMENTO_FISCAL CHAR(2)    ,
  VERSAO VARCHAR(30)    ,
  LE CHAR(1)    ,
  LEF CHAR(1)    ,
  MFD CHAR(1)    ,
  LACRE_NA_MFD CHAR(1)    ,
  DOCTO VARCHAR(60)    ,
  DATA_INSTALACAO_SB DATE    ,
  HORA_INSTALACAO_SB VARCHAR(8)      ,
PRIMARY KEY(ID));



CREATE TABLE ECF_RESOLUCAO (
  ID SERIAL  NOT NULL ,
  RESOLUCAO_TELA VARCHAR(20)    ,
  LARGURA INTEGER    ,
  ALTURA INTEGER    ,
  IMAGEM_TELA VARCHAR(50)    ,
  IMAGEM_MENU VARCHAR(50)    ,
  IMAGEM_SUBMENU VARCHAR(50)    ,
  HOTTRACK_COLOR VARCHAR(20)    ,
  ITEM_STYLE_FONT_NAME VARCHAR(20)    ,
  ITEM_STYLE_FONT_COLOR VARCHAR(20)    ,
  ITEM_SEL_STYLE_COLOR VARCHAR(20)    ,
  LABEL_TOTAL_GERAL_FONT_COLOR VARCHAR(20)    ,
  ITEM_STYLE_FONT_STYLE VARCHAR(20)    ,
  EDITS_COLOR VARCHAR(20)    ,
  EDITS_FONT_COLOR VARCHAR(20)    ,
  EDITS_DISABLED_COLOR VARCHAR(20)    ,
  EDITS_FONT_NAME VARCHAR(20)    ,
  EDITS_FONT_STYLE VARCHAR(20)      ,
PRIMARY KEY(ID));



CREATE TABLE SINTEGRA_60M (
  ID SERIAL  NOT NULL ,
  DATA_EMISSAO DATE    ,
  NUMERO_SERIE_ECF VARCHAR(20)    ,
  NUMERO_EQUIPAMENTO INTEGER    ,
  MODELO_DOCUMENTO_FISCAL CHAR(2)    ,
  COO_INICIAL INTEGER    ,
  COO_FINAL INTEGER    ,
  CRZ INTEGER    ,
  CRO INTEGER    ,
  VALOR_VENDA_BRUTA DECIMAL(18,6)    ,
  VALOR_GRANDE_TOTAL DECIMAL(18,6)      ,
PRIMARY KEY(ID));



CREATE TABLE SITUACAO_CLIENTE (
  ID SERIAL  NOT NULL ,
  NOME VARCHAR(20)    ,
  DESCRICAO VARCHAR(250)      ,
PRIMARY KEY(ID));



CREATE TABLE UNIDADE_PRODUTO (
  ID SERIAL  NOT NULL ,
  SIGLA VARCHAR(10)    ,
  DESCRICAO VARCHAR(250)    ,
  PODE_FRACIONAR CHAR(1)      ,
PRIMARY KEY(ID));



CREATE TABLE R06 (
  ID SERIAL  NOT NULL ,
  ID_OPERADOR INTEGER   NOT NULL ,
  ID_IMPRESSORA INTEGER   NOT NULL ,
  ID_ECF_CAIXA INTEGER    ,
  SERIE_ECF VARCHAR(20)    ,
  COO INTEGER    ,
  GNF INTEGER    ,
  GRG INTEGER    ,
  CDC INTEGER    ,
  DENOMINACAO CHAR(2)    ,
  DATA_EMISSAO DATE    ,
  HORA_EMISSAO VARCHAR(8)    ,
  LOGSS VARCHAR(32)      ,
PRIMARY KEY(ID));



CREATE TABLE LOG_IMPORTACAO (
  ID SERIAL  NOT NULL ,
  DATA_IMPORTACAO DATE    ,
  HORA_IMPORTACAO VARCHAR(8)    ,
  ERRO TEXT    ,
  REGISTRO TEXT      ,
PRIMARY KEY(ID));



CREATE TABLE R01 (
  ID SERIAL  NOT NULL ,
  SERIE_ECF VARCHAR(20)    ,
  CNPJ_EMPRESA VARCHAR(14)    ,
  CNPJ_SH VARCHAR(14)    ,
  INSCRICAO_ESTADUAL_SH VARCHAR(14)    ,
  INSCRICAO_MUNICIPAL_SH VARCHAR(14)    ,
  DENOMINACAO_SH VARCHAR(40)    ,
  NOME_PAF_ECF VARCHAR(40)    ,
  VERSAO_PAF_ECF VARCHAR(10)    ,
  MD5_PAF_ECF VARCHAR(32)    ,
  DATA_INICIAL DATE    ,
  DATA_FINAL DATE    ,
  VERSAO_ER VARCHAR(4)    ,
  NUMERO_LAUDO_PAF VARCHAR(40)    ,
  RAZAO_SOCIAL_SH VARCHAR(40)    ,
  ENDERECO_SH VARCHAR(40)    ,
  NUMERO_SH VARCHAR(10)    ,
  COMPLEMENTO_SH VARCHAR(40)    ,
  BAIRRO_SH VARCHAR(40)    ,
  CIDADE_SH VARCHAR(40)    ,
  CEP_SH VARCHAR(8)    ,
  UF_SH CHAR(2)    ,
  TELEFONE_SH VARCHAR(10)    ,
  CONTATO_SH VARCHAR(20)    ,
  PRINCIPAL_EXECUTAVEL VARCHAR(40)    ,
  LOGSS VARCHAR(32)      ,
PRIMARY KEY(ID));



CREATE TABLE R02 (
  ID SERIAL  NOT NULL ,
  ID_OPERADOR INTEGER   NOT NULL ,
  ID_IMPRESSORA INTEGER   NOT NULL ,
  ID_ECF_CAIXA INTEGER    ,
  SERIE_ECF VARCHAR(20)    ,
  CRZ INTEGER    ,
  COO INTEGER    ,
  CRO INTEGER    ,
  DATA_MOVIMENTO DATE    ,
  DATA_EMISSAO DATE    ,
  HORA_EMISSAO VARCHAR(8)    ,
  VENDA_BRUTA DECIMAL(18,6)    ,
  GRANDE_TOTAL DECIMAL(18,6)    ,
  LOGSS VARCHAR(32)      ,
PRIMARY KEY(ID));



CREATE TABLE ECF_EMPRESA (
  ID SERIAL  NOT NULL ,
  ID_EMPRESA INTEGER    ,
  RAZAO_SOCIAL VARCHAR(150)    ,
  NOME_FANTASIA VARCHAR(150)    ,
  CNPJ VARCHAR(14)    ,
  INSCRICAO_ESTADUAL VARCHAR(30)    ,
  INSCRICAO_ESTADUAL_ST VARCHAR(30)    ,
  INSCRICAO_MUNICIPAL VARCHAR(30)    ,
  INSCRICAO_JUNTA_COMERCIAL VARCHAR(30)    ,
  DATA_INSC_JUNTA_COMERCIAL DATE    ,
  MATRIZ_FILIAL CHAR(1)    ,
  DATA_CADASTRO DATE    ,
  DATA_INICIO_ATIVIDADES DATE    ,
  SUFRAMA VARCHAR(9)    ,
  EMAIL VARCHAR(250)    ,
  IMAGEM_LOGOTIPO TEXT    ,
  CRT CHAR(1)    ,
  TIPO_REGIME CHAR(1)    ,
  ALIQUOTA_PIS DECIMAL(18,6)    ,
  ALIQUOTA_COFINS DECIMAL(18,6)    ,
  LOGRADOURO VARCHAR(250)    ,
  NUMERO VARCHAR(6)    ,
  COMPLEMENTO VARCHAR(100)    ,
  CEP VARCHAR(8)    ,
  BAIRRO VARCHAR(100)    ,
  CIDADE VARCHAR(100)    ,
  UF CHAR(2)    ,
  FONE VARCHAR(10)    ,
  FAX VARCHAR(10)    ,
  CONTATO VARCHAR(30)    ,
  CODIGO_IBGE_CIDADE INTEGER    ,
  CODIGO_IBGE_UF INTEGER      ,
PRIMARY KEY(ID));



CREATE TABLE ECF_ALIQUOTAS (
  ID SERIAL  NOT NULL ,
  TOTALIZADOR_PARCIAL VARCHAR(10)    ,
  ECF_ICMS_ST VARCHAR(4)    ,
  PAF_P_ST CHAR(1)      ,
PRIMARY KEY(ID));



CREATE TABLE ECF_CAIXA (
  ID SERIAL  NOT NULL ,
  NOME VARCHAR(30)    ,
  DATA_CADASTRO DATE      ,
PRIMARY KEY(ID));



CREATE TABLE CFOP (
  ID SERIAL  NOT NULL ,
  CFOP INTEGER    ,
  DESCRICAO TEXT    ,
  APLICACAO TEXT      ,
PRIMARY KEY(ID));



CREATE TABLE BANCO (
  ID SERIAL  NOT NULL ,
  CODIGO VARCHAR(10)    ,
  NOME VARCHAR(100)    ,
  URL VARCHAR(250)      ,
PRIMARY KEY(ID));



CREATE TABLE ECF_E3 (
  ID SERIAL  NOT NULL ,
  SERIE_ECF VARCHAR(20)    ,
  MF_ADICIONAL CHAR(1)    ,
  TIPO_ECF VARCHAR(7)    ,
  MARCA_ECF VARCHAR(20)    ,
  MODELO_ECF VARCHAR(20)    ,
  DATA_ESTOQUE DATE    ,
  HORA_ESTOQUE VARCHAR(8)    ,
  LOGSS VARCHAR(32)      ,
PRIMARY KEY(ID));



CREATE TABLE PRODUTO (
  ID SERIAL  NOT NULL ,
  ID_UNIDADE_PRODUTO INTEGER   NOT NULL ,
  GTIN VARCHAR(14)    ,
  CODIGO_INTERNO VARCHAR(20)    ,
  NOME VARCHAR(100)    ,
  DESCRICAO VARCHAR(250)    ,
  DESCRICAO_PDV VARCHAR(30)    ,
  VALOR_VENDA DECIMAL(18,6)    ,
  QUANTIDADE_ESTOQUE DECIMAL(18,6)    ,
  ESTOQUE_MINIMO DECIMAL(18,6)    ,
  ESTOQUE_MAXIMO DECIMAL(18,6)    ,
  IAT CHAR(1)    ,
  IPPT CHAR(1)    ,
  NCM VARCHAR(8)    ,
  TIPO_ITEM_SPED CHAR(2)    ,
  TAXA_IPI DECIMAL(18,6)    ,
  TAXA_ISSQN DECIMAL(18,6)    ,
  TAXA_PIS DECIMAL(18,6)    ,
  TAXA_COFINS DECIMAL(18,6)    ,
  TAXA_ICMS DECIMAL(18,6)    ,
  CST CHAR(3)    ,
  CSOSN CHAR(4)    ,
  TOTALIZADOR_PARCIAL VARCHAR(10)    ,
  ECF_ICMS_ST VARCHAR(4)    ,
  CODIGO_BALANCA INTEGER    ,
  PAF_P_ST CHAR(1)    ,
  LOGSS VARCHAR(32)      ,
PRIMARY KEY(ID),
  FOREIGN KEY(ID_UNIDADE_PRODUTO)
    REFERENCES UNIDADE_PRODUTO(ID));

CREATE INDEX IFK_FK_UNIDADE_PRODUTO ON PRODUTO (ID_UNIDADE_PRODUTO);


CREATE TABLE SINTEGRA_60A (
  ID SERIAL  NOT NULL ,
  ID_SINTEGRA_60M INTEGER   NOT NULL ,
  SITUACAO_TRIBUTARIA VARCHAR(4)    ,
  VALOR DECIMAL(18,6)      ,
PRIMARY KEY(ID),
  FOREIGN KEY(ID_SINTEGRA_60M)
    REFERENCES SINTEGRA_60M(ID));

CREATE INDEX IFK_FK_60M_60A ON SINTEGRA_60A (ID_SINTEGRA_60M);


CREATE TABLE CLIENTE (
  ID SERIAL  NOT NULL ,
  ID_SITUACAO_CLIENTE INTEGER   NOT NULL ,
  NOME VARCHAR(150)    ,
  FANTASIA VARCHAR(150)    ,
  EMAIL VARCHAR(250)    ,
  CPF_CNPJ VARCHAR(14)    ,
  RG VARCHAR(20)    ,
  ORGAO_RG VARCHAR(20)    ,
  DATA_EMISSAO_RG DATE    ,
  SEXO CHAR(1)    ,
  INSCRICAO_ESTADUAL VARCHAR(30)    ,
  INSCRICAO_MUNICIPAL VARCHAR(30)    ,
  TIPO_PESSOA CHAR(1)    ,
  DATA_CADASTRO DATE    ,
  LOGRADOURO VARCHAR(250)    ,
  NUMERO VARCHAR(6)    ,
  COMPLEMENTO VARCHAR(50)    ,
  CEP VARCHAR(8)    ,
  BAIRRO VARCHAR(100)    ,
  CIDADE VARCHAR(100)    ,
  UF CHAR(2)    ,
  FONE1 VARCHAR(10)    ,
  FONE2 VARCHAR(10)    ,
  CELULAR VARCHAR(10)    ,
  CONTATO VARCHAR(50)    ,
  CODIGO_IBGE_CIDADE INTEGER    ,
  CODIGO_IBGE_UF INTEGER      ,
PRIMARY KEY(ID),
  FOREIGN KEY(ID_SITUACAO_CLIENTE)
    REFERENCES SITUACAO_CLIENTE(ID));

CREATE INDEX IFK_FK_SITUACAO_CLIENTE ON CLIENTE (ID_SITUACAO_CLIENTE);


CREATE TABLE R07 (
  ID SERIAL  NOT NULL ,
  ID_R06 INTEGER    ,
  CCF INTEGER    ,
  MEIO_PAGAMENTO VARCHAR(20)    ,
  VALOR_PAGAMENTO DECIMAL(18,6)    ,
  ESTORNO CHAR(1)    ,
  VALOR_ESTORNO DECIMAL(18,6)    ,
  LOGSS VARCHAR(32)      ,
PRIMARY KEY(ID),
  FOREIGN KEY(ID_R06)
    REFERENCES R06(ID));

CREATE INDEX IFK_FK_R06_R07 ON R07 (ID_R06);


CREATE TABLE R03 (
  ID SERIAL  NOT NULL ,
  ID_R02 INTEGER   NOT NULL ,
  SERIE_ECF VARCHAR(20)    ,
  TOTALIZADOR_PARCIAL VARCHAR(10)    ,
  VALOR_ACUMULADO DECIMAL(18,6)    ,
  CRZ INTEGER    ,
  LOGSS VARCHAR(32)      ,
PRIMARY KEY(ID),
  FOREIGN KEY(ID_R02)
    REFERENCES R02(ID));

CREATE INDEX IFK_FK_R02_R03 ON R03 (ID_R02);


CREATE TABLE ECF_CONTADOR (
  ID SERIAL  NOT NULL ,
  ID_ECF_EMPRESA INTEGER   NOT NULL ,
  CPF VARCHAR(11)    ,
  CNPJ VARCHAR(14)    ,
  NOME VARCHAR(100)    ,
  INSCRICAO_CRC VARCHAR(15)    ,
  FONE VARCHAR(15)    ,
  FAX VARCHAR(15)    ,
  LOGRADOURO VARCHAR(100)    ,
  NUMERO INTEGER    ,
  COMPLEMENTO VARCHAR(100)    ,
  BAIRRO VARCHAR(30)    ,
  CEP VARCHAR(8)    ,
  CODIGO_MUNICIPIO INTEGER    ,
  UF CHAR(2)    ,
  EMAIL VARCHAR(250)      ,
PRIMARY KEY(ID),
  FOREIGN KEY(ID_ECF_EMPRESA)
    REFERENCES ECF_EMPRESA(ID));

CREATE INDEX IFK_FK_EMPRESA_CONTADOR ON ECF_CONTADOR (ID_ECF_EMPRESA);


CREATE TABLE ECF_POSICAO_COMPONENTES (
  ID SERIAL  NOT NULL ,
  ID_ECF_RESOLUCAO INTEGER   NOT NULL ,
  NOME VARCHAR(100)    ,
  ALTURA INTEGER    ,
  LARGURA INTEGER    ,
  TOPO INTEGER    ,
  ESQUERDA INTEGER    ,
  TAMANHO_FONTE INTEGER  DEFAULT 0  ,
  TEXTO VARCHAR(250)      ,
PRIMARY KEY(ID),
  FOREIGN KEY(ID_ECF_RESOLUCAO)
    REFERENCES ECF_RESOLUCAO(ID));

CREATE INDEX IFK_FK_RES_POSICAO_COMPONENTES ON ECF_POSICAO_COMPONENTES (ID_ECF_RESOLUCAO);


CREATE TABLE ECF_OPERADOR (
  ID SERIAL  NOT NULL ,
  ID_ECF_FUNCIONARIO INTEGER   NOT NULL ,
  LOGIN VARCHAR(20)    ,
  SENHA VARCHAR(20)      ,
PRIMARY KEY(ID),
  FOREIGN KEY(ID_ECF_FUNCIONARIO)
    REFERENCES ECF_FUNCIONARIO(ID));

CREATE INDEX IFK_FK_FUNCIONARIO_OPERADOR ON ECF_OPERADOR (ID_ECF_FUNCIONARIO);


CREATE TABLE ECF_CHEQUE_CLIENTE (
  ID SERIAL  NOT NULL ,
  ID_BANCO INTEGER   NOT NULL ,
  ID_CLIENTE INTEGER   NOT NULL ,
  ID_ECF_MOVIMENTO INTEGER    ,
  NUMERO_CHEQUE INTEGER    ,
  DATA_CHEQUE DATE    ,
  VALOR_CHEQUE DECIMAL(18,6)    ,
  OBSERVACOES VARCHAR(250)    ,
  AGENCIA VARCHAR(15)    ,
  CONTA VARCHAR(15)    ,
  TIPO_CHEQUE CHAR(1)      ,
PRIMARY KEY(ID),
  FOREIGN KEY(ID_CLIENTE)
    REFERENCES CLIENTE(ID),
  FOREIGN KEY(ID_BANCO)
    REFERENCES BANCO(ID));

CREATE INDEX IFK_FK_CLIENTE_CHEQUE ON ECF_CHEQUE_CLIENTE (ID_CLIENTE);
CREATE INDEX IFK_FK_BANCO_CHEQUE ON ECF_CHEQUE_CLIENTE (ID_BANCO);


CREATE TABLE NOTA_FISCAL_CABECALHO (
  ID SERIAL  NOT NULL ,
  ID_ECF_FUNCIONARIO INTEGER   NOT NULL ,
  ID_CLIENTE INTEGER   NOT NULL ,
  CPF_CNPJ_CLIENTE VARCHAR(14)    ,
  CFOP INTEGER   NOT NULL ,
  NUMERO VARCHAR(6)    ,
  DATA_EMISSAO DATE    ,
  HORA_EMISSAO VARCHAR(8)    ,
  SERIE CHAR(2)    ,
  SUBSERIE CHAR(2)    ,
  TOTAL_PRODUTOS DECIMAL(18,6)    ,
  TOTAL_NF DECIMAL(18,6)    ,
  BASE_ICMS DECIMAL(18,6)    ,
  ICMS DECIMAL(18,6)    ,
  ICMS_OUTRAS DECIMAL(18,6)    ,
  ISSQN DECIMAL(18,6)    ,
  PIS DECIMAL(18,6)    ,
  COFINS DECIMAL(18,6)    ,
  IPI DECIMAL(18,6)    ,
  TAXA_ACRESCIMO DECIMAL(18,6)    ,
  ACRESCIMO DECIMAL(18,6)    ,
  ACRESCIMO_ITENS DECIMAL(18,6)    ,
  TAXA_DESCONTO DECIMAL(18,6)    ,
  DESCONTO DECIMAL(18,6)    ,
  DESCONTO_ITENS DECIMAL(18,6)    ,
  CANCELADA CHAR(1)    ,
  TIPO_NOTA CHAR(1)      ,
PRIMARY KEY(ID),
  FOREIGN KEY(ID_CLIENTE)
    REFERENCES CLIENTE(ID),
  FOREIGN KEY(ID_ECF_FUNCIONARIO)
    REFERENCES ECF_FUNCIONARIO(ID));

CREATE INDEX IFK_FK_CLIENTE_NF ON NOTA_FISCAL_CABECALHO (ID_CLIENTE);
CREATE INDEX IFK_FK_VENDEDOR_NF ON NOTA_FISCAL_CABECALHO (ID_ECF_FUNCIONARIO);


CREATE TABLE NOTA_FISCAL_DETALHE (
  ID SERIAL  NOT NULL ,
  ID_NF_CABECALHO INTEGER   NOT NULL ,
  ID_PRODUTO INTEGER   NOT NULL ,
  CFOP INTEGER   NOT NULL ,
  ITEM INTEGER    ,
  QUANTIDADE DECIMAL(18,6)    ,
  VALOR_UNITARIO DECIMAL(18,6)    ,
  VALOR_TOTAL DECIMAL(18,6)    ,
  BASE_ICMS DECIMAL(18,6)    ,
  TAXA_ICMS DECIMAL(18,6)    ,
  ICMS DECIMAL(18,6)    ,
  ICMS_OUTRAS DECIMAL(18,6)    ,
  ICMS_ISENTO DECIMAL(18,6)    ,
  TAXA_DESCONTO DECIMAL(18,6)    ,
  DESCONTO DECIMAL(18,6)    ,
  TAXA_ISSQN DECIMAL(18,6)    ,
  ISSQN DECIMAL(18,6)    ,
  TAXA_PIS DECIMAL(18,6)    ,
  PIS DECIMAL(18,6)    ,
  TAXA_COFINS DECIMAL(18,6)    ,
  COFINS DECIMAL(18,6)    ,
  TAXA_ACRESCIMO DECIMAL(18,6)    ,
  ACRESCIMO DECIMAL(18,6)    ,
  TAXA_IPI DECIMAL(18,6)    ,
  IPI DECIMAL(18,6)    ,
  CANCELADO CHAR(1)    ,
  CST CHAR(3)    ,
  MOVIMENTA_ESTOQUE CHAR(1)    ,
  ECF_ICMS_ST VARCHAR(4)      ,
PRIMARY KEY(ID),
  FOREIGN KEY(ID_NF_CABECALHO)
    REFERENCES NOTA_FISCAL_CABECALHO(ID),
  FOREIGN KEY(ID_PRODUTO)
    REFERENCES PRODUTO(ID));

CREATE INDEX IFK_FK_NF_CAB_DET ON NOTA_FISCAL_DETALHE (ID_NF_CABECALHO);
CREATE INDEX IFK_FK_PRODUTO_NF_DET ON NOTA_FISCAL_DETALHE (ID_PRODUTO);


CREATE TABLE ECF_CONFIGURACAO (
  ID SERIAL  NOT NULL ,
  ID_ECF_IMPRESSORA INTEGER   NOT NULL ,
  ID_ECF_RESOLUCAO INTEGER   NOT NULL ,
  ID_ECF_CAIXA INTEGER   NOT NULL ,
  ID_ECF_EMPRESA INTEGER   NOT NULL ,
  MENSAGEM_CUPOM VARCHAR(250)    ,
  PORTA_ECF CHAR(10)    ,
  IP_SERVIDOR VARCHAR(15)    ,
  IP_SITEF VARCHAR(15)    ,
  TIPO_TEF CHAR(2)    ,
  TITULO_TELA_CAIXA VARCHAR(100)    ,
  CAMINHO_IMAGENS_PRODUTOS VARCHAR(250)    ,
  CAMINHO_IMAGENS_MARKETING VARCHAR(250)    ,
  CAMINHO_IMAGENS_LAYOUT VARCHAR(250)    ,
  COR_JANELAS_INTERNAS VARCHAR(20)    ,
  MARKETING_ATIVO CHAR(1)    ,
  CFOP_ECF INTEGER    ,
  CFOP_NF2 INTEGER    ,
  TIMEOUT_ECF INTEGER    ,
  INTERVALO_ECF INTEGER    ,
  DESCRICAO_SUPRIMENTO VARCHAR(20)    ,
  DESCRICAO_SANGRIA VARCHAR(20)    ,
  TEF_TIPO_GP INTEGER    ,
  TEF_TEMPO_ESPERA INTEGER    ,
  TEF_ESPERA_STS INTEGER    ,
  TEF_NUMERO_VIAS INTEGER    ,
  DECIMAIS_QUANTIDADE INTEGER    ,
  DECIMAIS_VALOR INTEGER    ,
  BITS_POR_SEGUNDO INTEGER    ,
  QUANTIDADE_MAXIMA_CARTOES INTEGER    ,
  PESQUISA_PARTE CHAR(1)    ,
  ULTIMA_EXCLUSAO INTEGER    ,
  LAUDO VARCHAR(10)    ,
  DATA_ATUALIZACAO_ESTOQUE DATE    ,
  PEDE_CPF_CUPOM CHAR(1)    ,
  TIPO_INTEGRACAO INTEGER    ,
  TIMER_INTEGRACAO INTEGER    ,
  GAVETA_SINAL_INVERTIDO CHAR(1)    ,
  GAVETA_UTILIZACAO INTEGER    ,
  QUANTIDADE_MAXIMA_PARCELA INTEGER    ,
  IMPRIME_PARCELA CHAR(1)    ,
  USA_TECLADO_REDUZIDO CHAR(1)    ,
  PERMITE_LANCAR_NF_MANUAL CHAR(1)      ,
PRIMARY KEY(ID),
  FOREIGN KEY(ID_ECF_EMPRESA)
    REFERENCES ECF_EMPRESA(ID),
  FOREIGN KEY(ID_ECF_CAIXA)
    REFERENCES ECF_CAIXA(ID),
  FOREIGN KEY(ID_ECF_RESOLUCAO)
    REFERENCES ECF_RESOLUCAO(ID),
  FOREIGN KEY(ID_ECF_IMPRESSORA)
    REFERENCES ECF_IMPRESSORA(ID));

CREATE INDEX IFK_FK_EMPRESA_CONFIGURACAO ON ECF_CONFIGURACAO (ID_ECF_EMPRESA);
CREATE INDEX IFK_FK_CAIXA_CONFIGURACAO ON ECF_CONFIGURACAO (ID_ECF_CAIXA);
CREATE INDEX IFK_FK_RESOLUCAO_CONFIGURACAO ON ECF_CONFIGURACAO (ID_ECF_RESOLUCAO);
CREATE INDEX IFK_FK_IMPRESSORA_CONFIGURACAO ON ECF_CONFIGURACAO (ID_ECF_IMPRESSORA);


CREATE TABLE ECF_MOVIMENTO (
  ID SERIAL  NOT NULL ,
  ID_ECF_EMPRESA INTEGER   NOT NULL ,
  ID_ECF_TURNO INTEGER   NOT NULL ,
  ID_ECF_IMPRESSORA INTEGER   NOT NULL ,
  ID_ECF_OPERADOR INTEGER   NOT NULL ,
  ID_ECF_CAIXA INTEGER   NOT NULL ,
  ID_GERENTE_SUPERVISOR INTEGER   NOT NULL ,
  DATA_ABERTURA DATE    ,
  HORA_ABERTURA VARCHAR(8)    ,
  DATA_FECHAMENTO DATE    ,
  HORA_FECHAMENTO VARCHAR(8)    ,
  TOTAL_SUPRIMENTO DECIMAL(18,6)    ,
  TOTAL_SANGRIA DECIMAL(18,6)    ,
  TOTAL_NAO_FISCAL DECIMAL(18,6)    ,
  TOTAL_VENDA DECIMAL(18,6)    ,
  TOTAL_DESCONTO DECIMAL(18,6)    ,
  TOTAL_ACRESCIMO DECIMAL(18,6)    ,
  TOTAL_FINAL DECIMAL(18,6)    ,
  TOTAL_RECEBIDO DECIMAL(18,6)    ,
  TOTAL_TROCO DECIMAL(18,6)    ,
  TOTAL_CANCELADO DECIMAL(18,6)    ,
  STATUS_MOVIMENTO CHAR(1)   NOT NULL   ,
PRIMARY KEY(ID),
  FOREIGN KEY(ID_ECF_CAIXA)
    REFERENCES ECF_CAIXA(ID),
  FOREIGN KEY(ID_ECF_OPERADOR)
    REFERENCES ECF_OPERADOR(ID),
  FOREIGN KEY(ID_ECF_TURNO)
    REFERENCES ECF_TURNO(ID),
  FOREIGN KEY(ID_ECF_IMPRESSORA)
    REFERENCES ECF_IMPRESSORA(ID),
  FOREIGN KEY(ID_ECF_EMPRESA)
    REFERENCES ECF_EMPRESA(ID));

CREATE INDEX IFK_FK_CAIXA_MOVIMENTO ON ECF_MOVIMENTO (ID_ECF_CAIXA);
CREATE INDEX IFK_FK_OPERADOR_MOVIMENTO ON ECF_MOVIMENTO (ID_ECF_OPERADOR);
CREATE INDEX IFK_FK_TURNO_MOVIMENTO ON ECF_MOVIMENTO (ID_ECF_TURNO);
CREATE INDEX IFK_FK_IMPRESSORA_MOVIMENTO ON ECF_MOVIMENTO (ID_ECF_IMPRESSORA);
CREATE INDEX IFK_FK_EMPRESA_MOVIMENTO ON ECF_MOVIMENTO (ID_ECF_EMPRESA);


CREATE TABLE PRODUTO_PROMOCAO (
  ID SERIAL  NOT NULL ,
  ID_PRODUTO INTEGER   NOT NULL ,
  DATA_INICIO DATE    ,
  DATA_FIM DATE    ,
  QUANTIDADE_EM_PROMOCAO DECIMAL(18,6)    ,
  QUANTIDADE_MAXIMA_CLIENTE DECIMAL(18,6)    ,
  VALOR DECIMAL(18,6)      ,
PRIMARY KEY(ID),
  FOREIGN KEY(ID_PRODUTO)
    REFERENCES PRODUTO(ID));

CREATE INDEX IFK_FK_PRODUTO_PROMOCAO ON PRODUTO_PROMOCAO (ID_PRODUTO);


CREATE TABLE FICHA_TECNICA (
  ID SERIAL  NOT NULL ,
  ID_PRODUTO INTEGER   NOT NULL ,
  DESCRICAO VARCHAR(50)    ,
  ID_PRODUTO_FILHO INTEGER    ,
  QUANTIDADE DECIMAL(18,6)      ,
PRIMARY KEY(ID),
  FOREIGN KEY(ID_PRODUTO)
    REFERENCES PRODUTO(ID));

CREATE INDEX IFK_FK_PRODUTO_FICHA_TECNICA ON FICHA_TECNICA (ID_PRODUTO);


CREATE TABLE ECF_RELATORIO_GERENCIAL (
  ID SERIAL  NOT NULL ,
  ID_ECF_CONFIGURACAO INTEGER   NOT NULL ,
  X INTEGER    ,
  MEIOS_PAGAMENTO INTEGER    ,
  DAV_EMITIDOS INTEGER    ,
  IDENTIFICACAO_PAF INTEGER    ,
  PARAMETROS_CONFIGURACAO INTEGER    ,
  OUTROS INTEGER      ,
PRIMARY KEY(ID),
  FOREIGN KEY(ID_ECF_CONFIGURACAO)
    REFERENCES ECF_CONFIGURACAO(ID));

CREATE INDEX IFK_FK_CONFIG_REL_GER ON ECF_RELATORIO_GERENCIAL (ID_ECF_CONFIGURACAO);


CREATE TABLE ECF_SUPRIMENTO (
  ID SERIAL  NOT NULL ,
  ID_ECF_MOVIMENTO INTEGER   NOT NULL ,
  DATA_SUPRIMENTO DATE    ,
  VALOR DECIMAL(18,6)      ,
PRIMARY KEY(ID),
  FOREIGN KEY(ID_ECF_MOVIMENTO)
    REFERENCES ECF_MOVIMENTO(ID));

CREATE INDEX IFK_FK_MOVIMENTO_SUPRIMENTO ON ECF_SUPRIMENTO (ID_ECF_MOVIMENTO);


CREATE TABLE ECF_SANGRIA (
  ID SERIAL  NOT NULL ,
  ID_ECF_MOVIMENTO INTEGER   NOT NULL ,
  DATA_SANGRIA DATE    ,
  VALOR DECIMAL(18,6)      ,
PRIMARY KEY(ID),
  FOREIGN KEY(ID_ECF_MOVIMENTO)
    REFERENCES ECF_MOVIMENTO(ID));

CREATE INDEX IFK_FK_MOVIMENTO_SANGRIA ON ECF_SANGRIA (ID_ECF_MOVIMENTO);


CREATE TABLE ECF_RECEBIMENTO_NAO_FISCAL (
  ID SERIAL  NOT NULL ,
  ID_ECF_MOVIMENTO INTEGER   NOT NULL ,
  DATA_RECEBIMENTO DATE    ,
  DESCRICAO VARCHAR(50)    ,
  VALOR DECIMAL(18,6)      ,
PRIMARY KEY(ID),
  FOREIGN KEY(ID_ECF_MOVIMENTO)
    REFERENCES ECF_MOVIMENTO(ID));

CREATE INDEX IFK_FK_MOVIMENTO_RECBTO_NAO_FI ON ECF_RECEBIMENTO_NAO_FISCAL (ID_ECF_MOVIMENTO);


CREATE TABLE ECF_DOCUMENTOS_EMITIDOS (
  ID SERIAL  NOT NULL ,
  ID_ECF_MOVIMENTO INTEGER   NOT NULL ,
  DATA_EMISSAO DATE    ,
  HORA_EMISSAO VARCHAR(8)    ,
  TIPO CHAR(2)    ,
  COO INTEGER      ,
PRIMARY KEY(ID),
  FOREIGN KEY(ID_ECF_MOVIMENTO)
    REFERENCES ECF_MOVIMENTO(ID));

CREATE INDEX IFK_FK_MOVIMENTO_DOC_EMITIDOS ON ECF_DOCUMENTOS_EMITIDOS (ID_ECF_MOVIMENTO);


CREATE TABLE ECF_FECHAMENTO (
  ID SERIAL  NOT NULL ,
  ID_ECF_MOVIMENTO INTEGER   NOT NULL ,
  TIPO_PAGAMENTO VARCHAR(20)    ,
  VALOR DECIMAL(18,6)      ,
PRIMARY KEY(ID),
  FOREIGN KEY(ID_ECF_MOVIMENTO)
    REFERENCES ECF_MOVIMENTO(ID));

CREATE INDEX IFK_FK_MOVIMENTO_FECHAMENTO ON ECF_FECHAMENTO (ID_ECF_MOVIMENTO);


CREATE TABLE ECF_CONFIGURACAO_BALANCA (
  ID SERIAL  NOT NULL ,
  ID_ECF_CONFIGURACAO INTEGER   NOT NULL ,
  MODELO INTEGER    ,
  IDENTIFICADOR CHAR(1)    ,
  HAND_SHAKE INTEGER    ,
  PARITY INTEGER    ,
  STOP_BITS INTEGER    ,
  DATA_BITS INTEGER    ,
  BAUD_RATE INTEGER    ,
  PORTA CHAR(4)    ,
  TIMEOUT INTEGER    ,
  TIPO_CONFIGURACAO VARCHAR(20)      ,
PRIMARY KEY(ID),
  FOREIGN KEY(ID_ECF_CONFIGURACAO)
    REFERENCES ECF_CONFIGURACAO(ID));

CREATE INDEX IFK_FK_CONF_BALANCA ON ECF_CONFIGURACAO_BALANCA (ID_ECF_CONFIGURACAO);


CREATE TABLE ECF_CONFIGURACAO_LEITOR_SER (
  ID SERIAL  NOT NULL ,
  ID_ECF_CONFIGURACAO INTEGER   NOT NULL ,
  USA CHAR(1)    ,
  PORTA CHAR(4)    ,
  BAUD INTEGER    ,
  HAND_SHAKE INTEGER    ,
  PARITY INTEGER    ,
  STOP_BITS INTEGER    ,
  DATA_BITS INTEGER    ,
  INTERVALO INTEGER    ,
  USAR_FILA CHAR(1)    ,
  HARD_FLOW CHAR(1)    ,
  SOFT_FLOW CHAR(1)    ,
  SUFIXO VARCHAR(20)    ,
  EXCLUIR_SUFIXO CHAR(1)      ,
PRIMARY KEY(ID),
  FOREIGN KEY(ID_ECF_CONFIGURACAO)
    REFERENCES ECF_CONFIGURACAO(ID));

CREATE INDEX IFK_FK_CONF_LEITOR_SER ON ECF_CONFIGURACAO_LEITOR_SER (ID_ECF_CONFIGURACAO);


CREATE TABLE ECF_VENDA_CABECALHO (
  ID SERIAL  NOT NULL ,
  ID_CLIENTE INTEGER    ,
  ID_ECF_FUNCIONARIO INTEGER    ,
  ID_ECF_MOVIMENTO INTEGER   NOT NULL ,
  ID_ECF_DAV INTEGER    ,
  ID_ECF_PRE_VENDA_CABECALHO INTEGER    ,
  SERIE_ECF VARCHAR(20)    ,
  CFOP INTEGER   NOT NULL ,
  COO INTEGER    ,
  CCF INTEGER    ,
  DATA_VENDA DATE    ,
  HORA_VENDA VARCHAR(8)    ,
  VALOR_VENDA DECIMAL(18,6)    ,
  TAXA_DESCONTO DECIMAL(18,6)    ,
  DESCONTO DECIMAL(18,6)    ,
  TAXA_ACRESCIMO DECIMAL(18,6)    ,
  ACRESCIMO DECIMAL(18,6)    ,
  VALOR_FINAL DECIMAL(18,6)    ,
  VALOR_RECEBIDO DECIMAL(18,6)    ,
  TROCO DECIMAL(18,6)    ,
  VALOR_CANCELADO DECIMAL(18,6)    ,
  TOTAL_PRODUTOS DECIMAL(18,6)    ,
  TOTAL_DOCUMENTO DECIMAL(18,6)    ,
  BASE_ICMS DECIMAL(18,6)    ,
  ICMS DECIMAL(18,6)    ,
  ICMS_OUTRAS DECIMAL(18,6)    ,
  ISSQN DECIMAL(18,6)    ,
  PIS DECIMAL(18,6)    ,
  COFINS DECIMAL(18,6)    ,
  ACRESCIMO_ITENS DECIMAL(18,6)    ,
  DESCONTO_ITENS DECIMAL(18,6)    ,
  STATUS_VENDA CHAR(1)    ,
  NOME_CLIENTE VARCHAR(100)    ,
  CPF_CNPJ_CLIENTE VARCHAR(14)    ,
  CUPOM_CANCELADO CHAR(1)    ,
  LOGSS VARCHAR(32)      ,
PRIMARY KEY(ID),
  FOREIGN KEY(ID_ECF_MOVIMENTO)
    REFERENCES ECF_MOVIMENTO(ID),
  FOREIGN KEY(ID_ECF_FUNCIONARIO)
    REFERENCES ECF_FUNCIONARIO(ID),
  FOREIGN KEY(ID_CLIENTE)
    REFERENCES CLIENTE(ID));

CREATE INDEX IFK_FK_MOVIMENTO_VENDA_CAB ON ECF_VENDA_CABECALHO (ID_ECF_MOVIMENTO);
CREATE INDEX IFK_FK_VENDEDOR_VENDA ON ECF_VENDA_CABECALHO (ID_ECF_FUNCIONARIO);
CREATE INDEX IFK_FK_CLIENTE_VENDA ON ECF_VENDA_CABECALHO (ID_CLIENTE);


CREATE TABLE CONTA_RECEBER_CABECALHO (
  ID SERIAL  NOT NULL ,
  ID_ECF_VENDA_CABECALHO INTEGER   NOT NULL ,
  ID_PLANO_CONTAS INTEGER    ,
  ID_TIPO_DOCUMENTO INTEGER    ,
  ID_PESSOA INTEGER    ,
  TIPO CHAR(1)    ,
  NUMERO_DOCUMENTO VARCHAR(20)    ,
  VALOR DECIMAL(18,6)    ,
  DATA_LANCAMENTO DATE    ,
  PRIMEIRO_VENCIMENTO DATE    ,
  NATUREZA_LANCAMENTO CHAR(1)    ,
  QUANTIDADE_PARCELA INTEGER    ,
  CODIGO_TIPO_PAGAMENTO CHAR(2)      ,
PRIMARY KEY(ID),
  FOREIGN KEY(ID_ECF_VENDA_CABECALHO)
    REFERENCES ECF_VENDA_CABECALHO(ID));

CREATE INDEX IFK_FK_VENDA_CAB_CONTAS ON CONTA_RECEBER_CABECALHO (ID_ECF_VENDA_CABECALHO);


CREATE TABLE ECF_VENDA_DETALHE (
  ID SERIAL  NOT NULL ,
  ID_ECF_PRODUTO INTEGER   NOT NULL ,
  ID_ECF_VENDA_CABECALHO INTEGER   NOT NULL ,
  CFOP INTEGER   NOT NULL ,
  GTIN VARCHAR(14)    ,
  CCF INTEGER    ,
  COO INTEGER    ,
  SERIE_ECF VARCHAR(20)    ,
  ITEM INTEGER    ,
  QUANTIDADE DECIMAL(18,6)    ,
  VALOR_UNITARIO DECIMAL(18,6)    ,
  VALOR_TOTAL DECIMAL(18,6)    ,
  TOTAL_ITEM DECIMAL(18,6)    ,
  BASE_ICMS DECIMAL(18,6)    ,
  TAXA_ICMS DECIMAL(18,6)    ,
  ICMS DECIMAL(18,6)    ,
  TAXA_DESCONTO DECIMAL(18,6)    ,
  DESCONTO DECIMAL(18,6)    ,
  TAXA_ISSQN DECIMAL(18,6)    ,
  ISSQN DECIMAL(18,6)    ,
  TAXA_PIS DECIMAL(18,6)    ,
  PIS DECIMAL(18,6)    ,
  TAXA_COFINS DECIMAL(18,6)    ,
  COFINS DECIMAL(18,6)    ,
  TAXA_ACRESCIMO DECIMAL(18,6)    ,
  ACRESCIMO DECIMAL(18,6)    ,
  ACRESCIMO_RATEIO DECIMAL(18,6)    ,
  DESCONTO_RATEIO DECIMAL(18,6)    ,
  TOTALIZADOR_PARCIAL VARCHAR(10)    ,
  CST CHAR(3)    ,
  CANCELADO CHAR(1)    ,
  MOVIMENTA_ESTOQUE CHAR(1)    ,
  ECF_ICMS_ST VARCHAR(4)    ,
  LOGSS VARCHAR(32)    ,
  VALOR_IMPOSTO_FEDERAL DECIMAL(18,6)    ,
  VALOR_IMPOSTO_ESTADUAL DECIMAL(18,6)    ,
  VALOR_IMPOSTO_MUNICIPAL DECIMAL(18,6)      ,
PRIMARY KEY(ID),
  FOREIGN KEY(ID_ECF_VENDA_CABECALHO)
    REFERENCES ECF_VENDA_CABECALHO(ID),
  FOREIGN KEY(ID_ECF_PRODUTO)
    REFERENCES PRODUTO(ID));

CREATE INDEX IFK_FK_VENDA_CAB_DET ON ECF_VENDA_DETALHE (ID_ECF_VENDA_CABECALHO);
CREATE INDEX IFK_FK_PRODUTO_VENDA_DET ON ECF_VENDA_DETALHE (ID_ECF_PRODUTO);


CREATE TABLE ECF_TOTAL_TIPO_PAGAMENTO (
  ID SERIAL  NOT NULL ,
  ID_ECF_VENDA_CABECALHO INTEGER   NOT NULL ,
  ID_ECF_TIPO_PAGAMENTO INTEGER   NOT NULL ,
  DATA_VENDA DATE    ,
  SERIE_ECF VARCHAR(20)    ,
  COO INTEGER    ,
  CCF INTEGER    ,
  GNF INTEGER    ,
  VALOR DECIMAL(18,6)    ,
  NSU VARCHAR(30)    ,
  ESTORNO CHAR(1)    ,
  REDE VARCHAR(10)    ,
  CARTAO_DC CHAR(1)    ,
  LOGSS VARCHAR(32)      ,
PRIMARY KEY(ID),
  FOREIGN KEY(ID_ECF_TIPO_PAGAMENTO)
    REFERENCES ECF_TIPO_PAGAMENTO(ID),
  FOREIGN KEY(ID_ECF_VENDA_CABECALHO)
    REFERENCES ECF_VENDA_CABECALHO(ID));

CREATE INDEX IFK_FK_TIPO_PGTO_TOTAL ON ECF_TOTAL_TIPO_PAGAMENTO (ID_ECF_TIPO_PAGAMENTO);
CREATE INDEX IFK_FK_VENDA_CAB_TOTAL_TIPO_PG ON ECF_TOTAL_TIPO_PAGAMENTO (ID_ECF_VENDA_CABECALHO);


CREATE TABLE CONTA_RECEBER_DETALHE (
  ID SERIAL  NOT NULL ,
  ID_CONTA_RECEBER_CABECALHO INTEGER   NOT NULL ,
  ID_MEIOS_PAGAMENTO INTEGER    ,
  ID_CHEQUE_EMITIDO INTEGER    ,
  ID_CONTA_CAIXA INTEGER    ,
  DATA_EMISSAO DATE    ,
  DATA_VENCIMENTO DATE    ,
  DATA_PAGAMENTO DATE    ,
  NUMERO_PARCELA INTEGER    ,
  VALOR DECIMAL(18,6)    ,
  TAXA_JUROS DECIMAL(18,6)    ,
  TAXA_MULTA DECIMAL(18,6)    ,
  TAXA_DESCONTO DECIMAL(18,6)    ,
  VALOR_JUROS DECIMAL(18,6)    ,
  VALOR_MULTA DECIMAL(18,6)    ,
  VALOR_DESCONTO DECIMAL(18,6)    ,
  TOTAL_PARCELA DECIMAL(18,6)    ,
  HISTORICO TEXT    ,
  SITUACAO CHAR(1)      ,
PRIMARY KEY(ID),
  FOREIGN KEY(ID_CONTA_RECEBER_CABECALHO)
    REFERENCES CONTA_RECEBER_CABECALHO(ID));

CREATE INDEX IFK_FK_CONTAS_PARCELAS ON CONTA_RECEBER_DETALHE (ID_CONTA_RECEBER_CABECALHO);



